server:
  port: 8001

eureka:
  instance:
    hostname: localhost # 主机名
    prefer-ip-address: true # 将当前实例的ip注册到eureka server中。默认未false 注册主机名。
    ip-address: 127.0.0.1 # 设置当前实例的ip。
    instance-id: ${eureka.instance.ip-address}:${spring.application.name}:${server.port}
    lease-renewal-interval-in-seconds: 3 # 每隔3s发一次心跳
    lease-expiration-duration-in-seconds: 9 #如果9s没有发送心跳，请服务器删除
  client:
    register-with-eureka: true # 是否将自己的路径注册到eureka上。
    fetch-registry: true # 是否需要从eureka中抓去数据。
    service-url:
      defaultZone: http://localhost:8762/eureka # eureka服务端地址

spring:
  application:
    name: eureka-provider

pandaz: you are the best coder!
